-- ============================================================
-- NCR HOME TUITION - CLEAR OLD DATA
-- ============================================================
-- WARNING: This deletes ALL records from these tables.
-- Run this in Supabase SQL Editor BEFORE uploading new CSV.
-- ============================================================

-- Clear all old data
DELETE FROM students;
DELETE FROM tutors;
DELETE FROM payments;
DELETE FROM admin_sessions;
DELETE FROM admins;

-- Reset auto-increment if any (Supabase/PostgreSQL uses sequences,
-- but since we use TEXT primary keys, there's nothing to reset).
-- The next ID will be auto-generated by the backend based on
-- existing records (NCR001, TECH001, etc.).

-- Verify tables are empty
SELECT 'students' as tbl, COUNT(*) as count FROM students
UNION ALL
SELECT 'tutors', COUNT(*) FROM tutors
UNION ALL
SELECT 'payments', COUNT(*) FROM payments
UNION ALL
SELECT 'admins', COUNT(*) FROM admins;
